name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This is correct if your default branch is 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '16'  # This is fine if your project uses Node.js 16

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # This is correct for Next.js static export